# .bashrc

export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/dev/go/bin:$PATH"
export PATH="$HOME/bin/lua/bin:$PATH"
export GOPATH=$HOME/dev/go

alias gitdff="git diff --shortstat"

PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null)'; PS1='\u@\h \w ${PS1_CMD1}\n฿ '
