# .bashrc

export GOPATH="$HOME/dev/bin/go"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/dev/bin/luals/bin:$PATH"

alias gitdff="git diff --shortstat"

PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null)'; PS1='\u@\h \w ${PS1_CMD1}\n฿ '
